## Repaso Numpy y Pandas

In [14]:
import numpy as np
import pandas as pd
#1. Crea un array de 5x2 con los valores desde 100 hasta 200 de 10 en 10
five_tow= np.array(np.arange(100,200,10))
five_tow.reshape(5,2)


array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [2]:
#2. Redimensiona el array a 3x3 (se debe de eliminar el último elemento)
three_three= np.delete(five_tow,-1) #delete the last item
prueba=three_three.reshape(3,3)
print(prueba)

[[100 110 120]
 [130 140 150]
 [160 170 180]]


In [3]:
#3. Crea un array con los elementos de la tercera posición de cada fila
third_position=prueba[:,2]
print(third_position)

[120 150 180]


In [26]:
#4. Muestra los elementos de las filas de posición par y columna de posición impar
par_impar = pd.DataFrame(prueba)
print('Imprime las filas pares:',par_impar.iloc[[0,2]])

print('Imprime las columnas impares:')
par_impar.iloc[:, 1] 


Imprime las filas pares:      0    1    2
0  100  110  120
2  160  170  180
Imprime las columnas impares:


0    110
1    140
2    170
Name: 1, dtype: int32

In [51]:
#5. Crea dos arrays de 2x3. Posteriormente suma los dos arrays y a su resultado eleva al cuadrado cada elemento
array_one = np.array([[5,6,28],[10,25,36]]) #array ejemplo mio
array_tow = np.random.rand(2,3) #array aleatoria
suma_arrays = array_one+array_tow #suma de ambas arrays

print(np.square(suma_arrays)) #square eleva al cuadrado cada elemento de la array 

[[0.61403945 0.91126952 0.28833251]
 [0.19130937 0.23225116 0.90943421]]
[[  31.51743892   47.76564631  800.22975633]
 [ 103.86278676  636.66649839 1362.30633405]]


In [4]:
#6. Crea un array de 8x3. Posteriormente dividelo en 4 subarrays
array_three = np.random.randint(1,30 ,(8,3))
print(array_three)
print(array_three.reshape(2,3))


[[23 20 29]
 [12 19 23]
 [21  6 20]
 [ 9 16 17]
 [12  9 23]
 [16 27 16]
 [14  2 17]
 [21 24 26]]


ValueError: cannot reshape array of size 24 into shape (2,3)

In [271]:
#7. Dado un array de 3x3. Crea un nuevo array con este ordenado por la 2ª fila y otro array con este array ordenado por la 2ª columna
array_four = np.random.randint(1,10, (3,3))
print(array_four)
array_orden_fila = array_four[array_four[:, 1].argsort()]
print(array_orden_fila)


[[5 9 9]
 [7 8 7]
 [3 9 1]]
[[7 8 7]
 [5 9 9]
 [3 9 1]]


In [144]:
#8. Dado un array de 3x3. Devuelve sus mínimos de cada columna y el máximo de cada fila
array = np.array([[2,5,9],[89,41,75],[98,1,45]])
print(array)
min_column = array.min(axis=0)
max_row = array.max(axis=1)

print("Minimum of each Column\n",min_column)
print("Maximum of each Row\n",max_row)


[[ 2  5  9]
 [89 41 75]
 [98  1 45]]
Minimum of each Column
 [2 1 9]
Maximum of each Row
 [ 9 89 98]


In [154]:
#9. Dado un array de 3x3 elimina su 2ª columna y añadela al inicio
print('Array ejercicio 8:')
print(array)
array[:, [1, 0]] = array[:, [0, 1]]
print('Resultado de eliminar y añadir segunda columna:')
print(array)

Array ejercicio 8:
[[ 5  2  9]
 [41 89 75]
 [ 1 98 45]]
Resultado de eliminar y añadir segunda columna:
[[ 2  5  9]
 [89 41 75]
 [98  1 45]]


In [15]:
#10. Crea un DataFrame con la información de *coches.csv*
read_car = pd.read_csv('coches.csv')
read_car


index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
..    ...          ...          ...         ...     ...         ...   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
0              four         111               21  13495.0  
1              four         111               21  16500.0  
2               six         154               19  16500.0  
3              four         102               24  13950.0  
4              five         115               18  17450.0  
..              ...         ...              ...      ...  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0  

[61 rows x 10 columns]

In [273]:
#11. Muestra la compañía que tenga el coche más caro
max_value_column = read_car["price"].max()
print(max_value_column)
print('Compañia que tiene el coche mas caro: ')
read_car['company'][read_car['price'] == 45400.00]

45400.0
Compañia que tiene el coche mas caro: 


35    mercedes-benz
Name: company, dtype: object

In [12]:
#12. Muestra todos los coches de Toyota

df_toyota = read_car.loc[:,'company'] == 'toyota' 
car_toyota = read_car.loc[df_toyota]
car_toyota


index company body-style  wheel-base  length engine-type num-of-cylinders  \
48     66  toyota  hatchback        95.7   158.7         ohc             four   
49     67  toyota  hatchback        95.7   158.7         ohc             four   
50     68  toyota  hatchback        95.7   158.7         ohc             four   
51     69  toyota      wagon        95.7   169.7         ohc             four   
52     70  toyota      wagon        95.7   169.7         ohc             four   
53     71  toyota      wagon        95.7   169.7         ohc             four   
54     79  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage    price  
48          62               35   5348.0  
49          62               31   6338.0  
50          62               31   6488.0  
51          62               31   6918.0  
52          62               27   7898.0  
53          62               27   8778.0  
54         156               19  15750.0

In [10]:
#13. Muestra cuántos coches tiene cada compañía
read_car.value_counts('company') 

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
dtype: int64

In [16]:
#14. Muestra todas las compañías con su precio más caro

### ESTE ME DOY POR VENCIDA PORQUE NO SE SI SERA YA POR QUERER HACERLO SUPER REDUCIDO O ESTOY ATASCADA 
read_car.groupby(["company"])[["company","price"]].agg({"price":np.max})


price
company               
alfa-romero    16500.0
audi           18920.0
bmw            41315.0
chevrolet       6575.0
dodge           6377.0
honda          12945.0
isuzu           6785.0
jaguar         36000.0
mazda          18344.0
mercedes-benz  45400.0
mitsubishi      8189.0
nissan         13499.0
porsche        37028.0
toyota         15750.0
volkswagen      9995.0
volvo          13415.0

In [265]:
#15. Calcula la media de kilometros de cada compañía

read_car['company'].value_counts()
print(read_car['average-mileage'][read_car['company'] == 'toyota'].mean())
print(read_car['average-mileage'][read_car['company'] == 'bmw'].mean())
print(read_car['average-mileage'][read_car['company'] == 'mazda'].mean())
print(read_car['average-mileage'][read_car['company'] == 'nissan'].mean())
print(read_car['average-mileage'][read_car['company'] == 'audi'].mean())
print(read_car['average-mileage'][read_car['company'] == 'mercedes-benz'].mean())
print(read_car['average-mileage'][read_car['company'] == 'mitsubishi'].mean())
print(read_car['average-mileage'][read_car['company'] == 'volkswagen'].mean())
print(read_car['average-mileage'][read_car['company'] == 'alfa-romero'].mean())
print(read_car['average-mileage'][read_car['company'] == 'chevrolet'].mean())
print(read_car['average-mileage'][read_car['company'] == 'honda'].mean())
print(read_car['average-mileage'][read_car['company'] == 'isuzu'].mean())
print(read_car['average-mileage'][read_car['company'] == 'jaguar'].mean())
print(read_car['average-mileage'][read_car['company'] == 'porsche'].mean())
print(read_car['average-mileage'][read_car['company'] == 'dodge'].mean())
print(read_car['average-mileage'][read_car['company'] == 'volvo'].mean())



28.714285714285715
19.0
28.0
31.4
20.0
18.0
29.5
31.75
20.333333333333332
41.0
26.333333333333332
33.333333333333336
14.333333333333334
17.0
31.0
23.0


In [224]:
#16. Ordena los coches por precio
read_car.sort_values('price')


index        company   body-style  wheel-base  length engine-type  \
13     16      chevrolet    hatchback        88.4   141.1           l   
27     36          mazda    hatchback        93.1   159.1         ohc   
48     66         toyota    hatchback        95.7   158.7         ohc   
36     49     mitsubishi    hatchback        93.7   157.3         ohc   
28     37          mazda    hatchback        93.1   159.1         ohc   
37     50     mitsubishi    hatchback        93.7   157.3         ohc   
17     20          dodge    hatchback        93.7   157.3         ohc   
14     17      chevrolet    hatchback        94.5   155.9         ohc   
49     67         toyota    hatchback        95.7   158.7         ohc   
16     19          dodge    hatchback        93.7   157.3         ohc   
50     68         toyota    hatchback        95.7   158.7         ohc   
15     18      chevrolet        sedan        94.5   158.8         ohc   
41     54         nissan        sedan        94.5   165.3         ohc   
21     30          isuzu        sedan        94.3   170.7         ohc   
29     38          mazda    hatchback        93.1   159.1         ohc   
42     55         nissan        sedan        94.5   165.3         ohc   
51     69         toyota        wagon        95.7   169.7         ohc   
38     51     mitsubishi        sedan        96.3   172.4         ohc   
40     53         nissan        sedan        94.5   165.3         ohc   
18     27          honda        wagon        96.5   157.1         ohc   
43     56         nissan        wagon        94.5   170.2         ohc   
55     80     volkswagen        sedan        97.3   171.7         ohc   
52     70         toyota        wagon        95.7   169.7         ohc   
56     81     volkswagen        sedan        97.3   171.7         ohc   
57     82     volkswagen        sedan        97.3   171.7         ohc   
39     52     mitsubishi        sedan        96.3   172.4         ohc   
53     71         toyota        wagon        95.7   169.7         ohc   
58     86     volkswagen        sedan        97.3   171.7         ohc   
20     29          honda        sedan        96.5   169.1         ohc   
30     39          mazda    hatchback        95.3   169.0       rotor   
59     87          volvo        sedan       104.3   188.8         ohc   
19     28          honda        sedan        96.5   175.4         ohc   
60     88          volvo        wagon       104.3   188.8         ohc   
0       0    alfa-romero  convertible        88.6   168.8        dohc   
44     57         nissan        sedan       100.4   184.6        ohcv   
3       3           audi        sedan        99.8   176.6         ohc   
5       5           audi        sedan        99.8   177.3         ohc   
54     79         toyota        wagon       104.5   187.8        dohc   
7       9            bmw        sedan       101.2   176.8         ohc   
1       1    alfa-romero  convertible        88.6   168.8        dohc   
2       2    alfa-romero    hatchback        94.5   171.2        ohcv   
8      10            bmw        sedan       101.2   176.8         ohc   
4       4           audi        sedan        99.4   176.6         ohc   
31     43          mazda        sedan       104.9   175.0         ohc   
6       6           audi        wagon       105.8   192.7         ohc   
9      11            bmw        sedan       101.2   176.8         ohc   
32     44  mercedes-benz        sedan       110.0   190.9         ohc   
33     45  mercedes-benz        wagon       110.0   190.9         ohc   
10     13            bmw        sedan       103.5   189.0         ohc   
24     33         jaguar        sedan       113.0   199.6        dohc   
45     61        porsche      hardtop        89.5   168.9        ohcf   
25     34         jaguar        sedan       113.0   199.6        dohc   
26     35         jaguar        sedan       102.0   191.7        ohcv   
12     15            bmw        sedan       110.0   197.0     