## Repaso Numpy y Pandas

In [65]:
import numpy as np
import pandas as pd
#1. Crea un array de 5x2 con los valores desde 100 hasta 200 de 10 en 10
five_tow= np.array(np.arange(100,200,10))
five_tow.reshape(5,2)




array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [91]:
#2. Redimensiona el array a 3x3 (se debe de eliminar el último elemento)
three_three= np.delete(five_tow,-1) #delete the last item
prueba=three_three.reshape(3,3)
print(prueba)


[[100 110 120]
 [130 140 150]
 [160 170 180]]


In [92]:
#3. Crea un array con los elementos de la tercera posición de cada fila
third_position=prueba[:,2]
print(third_position)

[120 150 180]


In [95]:
#4. Muestra los elementos de las filas de posición par y columna de posición impar
prueba.iloc[0:5] # Primeras cinco filas
prueba.iloc[:, 0:5] # Primeras cinco columnas
prueba.iloc[[0,2,1]]  # Primera, tercera y segunda filas
prueba.iloc[:, [0,2,1]]  # Primera, tercera y segunda columnas

AttributeError: 'numpy.ndarray' object has no attribute 'loc'

In [ ]:
#5. Crea dos arrays de 2x3. Posteriormente suma los dos arrays y a su resultado eleva al cuadrado cada elemento

In [ ]:
#6. Crea un array de 8x3. Posteriormente dividelo en 4 subarrays

In [ ]:
#7. Dado un array de 3x3. Crea un nuevo array con este ordenado por la 2ª fila y otro array con este array ordenado por la 2ª columna

In [ ]:
#8. Dado un array de 3x3. Devuelve sus mínimos de cada columna y el máximo de cada fila

In [ ]:
#9. Dado un array de 3x3 elimina su 2ª columna y añadela al inicio

In [ ]:
#10. Crea un DataFrame con la información de *coches.csv*

In [ ]:
#11. Muestra la compañía que tenga el coche más caro

In [ ]:
#12. Muestra todos los coches de Toyota

In [ ]:
#13. Muestra cuántos coches tiene cada compañía

In [ ]:
#14. Muestra todas las compañías con su precio más caro

In [ ]:
#15. Calcula la media de kilometros de cada compañía

16. Ordena los coches por precio