In [1]:
import numpy as np

In [2]:
#1. Crea un vector de ceros de 10 elementos excepto el quinto elemento que debe de ser 1
vect1 = np.zeros((10), dtype=float)
vect1[4:5] = 1
vect1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [65]:
#2. Crea un vector con los valores desde el 10 hasta 49
vect2 = np.arange(10,50)
vect2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [42]:
#3. Modifica el vector del ejercicio anterior y calcula el inverso
modified_vector= vect2[::-1]
modified_vector


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [66]:
#4. Crea una matriz de 3x3 con los valores desde 0 hasta 8
mat1 = np.arange(0,9).reshape(3,3)
mat1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
#5. Crea una matriz de identidad de 4x4
print(np.identity(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [63]:
#6. Crea una matriz de 5x5x5 con valores aleatorios
N = 5
M = 5
S = 5
m = [[np.random.randint(1,10) for j in range(M)] for i in range(N) for x in range(S)]
m


[[9, 7, 1, 2, 4],
 [1, 5, 7, 2, 1],
 [8, 8, 3, 1, 4],
 [9, 8, 6, 2, 6],
 [1, 2, 3, 9, 4],
 [1, 3, 1, 9, 3],
 [2, 2, 6, 6, 8],
 [5, 2, 6, 3, 1],
 [6, 1, 3, 2, 6],
 [3, 1, 5, 1, 1],
 [9, 1, 8, 1, 4],
 [4, 2, 4, 4, 3],
 [3, 7, 4, 9, 9],
 [6, 3, 4, 1, 3],
 [7, 3, 2, 1, 7],
 [7, 5, 6, 8, 2],
 [1, 3, 8, 8, 4],
 [4, 3, 6, 5, 3],
 [3, 3, 4, 2, 7],
 [6, 6, 8, 6, 2],
 [3, 7, 9, 7, 2],
 [8, 1, 8, 6, 7],
 [9, 1, 9, 4, 6],
 [6, 4, 6, 2, 9],
 [5, 6, 5, 6, 1]]

In [59]:
#7. Calcula la media del vector anterior
print(np.mean(m, dtype = np.float64))

4.552


In [82]:
#8. Crea una matriz 3x3 con los valores 1,2,3 en la diagonal (el resto de elementos deben de ser 0)
mat_diago = np.zeros((3, 3),int)
np.fill_diagonal(mat_diago,[1,2,3])
mat_diago


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [91]:
#9. Crea una matriz 4x4 con los valores 1,2,3 en la diagonal inferior (el resto de elementos deben de ser 0)
#[[0, 0, 0, 0],
#[1, 0, 0, 0],
#[0, 2, 0, 0],
#[0, 0, 3, 0]]

# np.eye(4, k=-1, dtype='float', order='C') --- Esta forma la he buscado para saber especificament de donde sale todo y como indiciarlo en proximas
np.diag([1,2,3], k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [97]:
#10. Normaliza una matriz de 4x4 con valores aleatorios
np.random.randint(3, 30, size = (4,4))

array([[11, 20,  9, 13],
       [14, 19, 28, 11],
       [15, 14, 26, 19],
       [13, 18,  4, 26]])

In [129]:
#11. Multiplica una matriz de 6x3 (todos valores a 1) por una de 3x2 (todos valores a 1)
a = np.ones((6,3))
b = np.ones((3,2))
print(a@b)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [130]:
#12. Realiza la multiplicación del ejercicio anterior utilizando un operador
a = np.ones((6,3))
b = np.ones((3,2))
print(a.dot(b))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [2]:
#13. Cree una matriz de 1 dimensión con los valores desde 1 a 10, con los valores desde 3 hasta 8 en negativo. [1, 2 , -3, -4, -5, -6, -7, -8, 9, 10]

mat_neg = np.arange(1,11)
mat_neg[2:8]=[-10]
mat_neg
# array2=np.arange(1,11)
# array2[(array2>=3)&(array2<=8)]*=-1

NameError: name 'np' is not defined

In [159]:
#14. Cree un vector de 10 elementos con los valores aleatorios entre 0 y 10
np.random.randint(1,10, size=10)

array([7, 6, 4, 7, 3, 3, 4, 8, 8, 4])

In [407]:
#15. Cree un vector con todas las fechas de abril de 2022
date_time = np.arange('2005-04', '2005-05', dtype='datetime64[D]')
date_time

array(['2005-04-01', '2005-04-02', '2005-04-03', '2005-04-04',
       '2005-04-05', '2005-04-06', '2005-04-07', '2005-04-08',
       '2005-04-09', '2005-04-10', '2005-04-11', '2005-04-12',
       '2005-04-13', '2005-04-14', '2005-04-15', '2005-04-16',
       '2005-04-17', '2005-04-18', '2005-04-19', '2005-04-20',
       '2005-04-21', '2005-04-22', '2005-04-23', '2005-04-24',
       '2005-04-25', '2005-04-26', '2005-04-27', '2005-04-28',
       '2005-04-29', '2005-04-30'], dtype='datetime64[D]')

In [163]:
#16. Crea un vector ordenado de 15 elementos con valores aleatorios entre 1 y 10
order= np.random.randint(1,10, size=15)
order.sort()
print(order)


[1 2 2 3 3 4 4 4 4 5 5 5 6 7 7]


In [176]:
#17. Devuelva la suma de los valores del vector del ejercicio anterior
sum = np.sum(order)
sum

62

In [177]:
#18. Devuelve el resultado de la suma del vector ejercicio 16 de una forma más rápida que utilizar np.sum
print(sum)

62


In [228]:
#19. Crea un vector aleatorio de tamaño 20 y reemplaza el máximo valor por 0
aleatorio =np.random.randn(20)
print(aleatorio)
#Indico el array que ha creado aleatoriamente ya que cada vez que se ejecuta, genera un vector aleatorio por lo que el valor a reemplazar cambiar de argumento y de maximo valor
# [ 1.24629465  0.86585994 -0.76152494 -1.02830821 -1.76175274  0.16497846
#   1.0144932   0.08566192  0.77009875  1.04197093 -1.5265696  -1.56880638
#  -0.37342594  0.09992539 -0.96933534  0.05378979 -2.31207458 -0.08109476
#  -0.12997653  1.04972073]
print(aleatorio.argmax())
aleatorio[4]=0
aleatorio

[-0.13773525  0.0034881  -0.73757227  1.89797379 -0.13356839  0.81064007
  1.81410872  0.05017401 -0.12613517 -0.61966979 -0.93211565  0.7961741
  0.3250071   0.78254407  0.45220763 -1.38933255  1.02371811  0.25066622
  0.97991169 -1.00064944]
3


array([-0.13773525,  0.0034881 , -0.73757227,  1.89797379,  0.        ,
        0.81064007,  1.81410872,  0.05017401, -0.12613517, -0.61966979,
       -0.93211565,  0.7961741 ,  0.3250071 ,  0.78254407,  0.45220763,
       -1.38933255,  1.02371811,  0.25066622,  0.97991169, -1.00064944])

In [229]:
#20. Itera un numpy arrays mostrando su posición y el valor
np_arrays = np.array((1, 5, 9, 3, 7, 2, 0))
np.where(np_arrays == 5)

(array([1], dtype=int64),)

In [232]:
#21. Resta a cada elemento la media calculada de su fila de la matriz
np_media = np.mean(np_arrays)
np_arrays-np_media

array([-2.85714286,  1.14285714,  5.14285714, -0.85714286,  3.14285714,
       -1.85714286, -3.85714286])

In [400]:
#22. Crea una matriz de 6x6 y ordenala por la 4ª fila
mat7 = np.random.randint(0, 60, size=(6,6))
print(mat7)
print(mat7.sort(axis=0))

#ESTE EJERCICIO NECESITO REVISARLO YA QUE IGUAL QUE EL 24 ME GENERA YA CONFUSION A LA HORA DE DESARROLLARLO, SEGURO QUE ES ALGO MAS SENCILLO Y NO SOY CAPAZ DE HACERLO


[[ 3  4 55 12 45  4]
 [28 27 11 56 35 40]
 [49 18 22 25 31  7]
 [40 43  4 22  3 56]
 [57  7 31 16 49  4]
 [46 24 32 55 50 58]]
None


In [353]:
#23. Existiendo el vector [1, 2, 3, 4, 5], construir un nuevo vector con 3 ceros consecuitovs entre cada valor del vector anterior
vect = [1,2,3,4,5]
vect_new = []
for x in a:
    vect_new.extend([x, 0, 0, 0])
print(vect_new)
#otro metodo de realizarlo añadiendo los ceros al nuevo vector 
vect2 = np.array(vect_new)
print(vect2)

#este se puede hacer con la funcon flatten para devolver una matriz unidimensional aunque estemos utilizando un vector en este caso
# np.array([[n, 0,0,0] for n in a]).flatten()




[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]


In [376]:
#24. Crea un vector con números aleatorios de 5x5 e intercambia la fila segunda por la tercera
b= np.random.randint(0, 60, size=(5,5))
print(b)
print(b.transpose())

#ESTE NECESITO REVISARLO PORQUE INVESTIGUE Y ENTENDI EL METODO TRANSPOSE PERO NO ERA YA CAPAZ DE CAMBIAR UNA FILA POR OTRA AUNQUE CONTROLE EL ARGUMENTO Y AXIS = 0


[[38 47 46 48 48]
 [44 42  1  0 48]
 [42 42 45 44 40]
 [35 23 32 29  7]
 [54 52 20 10 21]]
[[38 44 42 35 54]
 [47 42 42 23 52]
 [46  1 45 32 20]
 [48  0 44 29 10]
 [48 48 40  7 21]]
