In [8]:
#1. Define un ndarray de una dimensión con los valores 100, 1, 1001 y 123.
import numpy as np
arr = np.array([100,1,1001,123])

In [9]:
#2. Muestra los valores desde el primer elemento hasta el cuarto incluido.
arr[:]

array([ 100,    1, 1001,  123])

In [35]:
#3. Muestra el valor de la primera posición.
arr[1]

1

In [40]:
#4. Define un ndarray con dos filas y cuatro columnas con los valores [1,1,1,1] y [2,2,2,2].
mat=np.array([[1, 1, 1, 1],[2, 2, 2, 2]])
mat

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [53]:
#5. Muestra los dos primeros valores.
print(mat[:,0:2])


[[1 1]
 [2 2]]


In [47]:
#6. Muestra el valor de la primera fila y primera columna.
mat[0][0] 

1

In [46]:
#7. Muestra los valores que sean mayores que 1.
mat > 1
mat[mat> 1]

array([2, 2, 2, 2])