In [12]:
#1. Defina un ndarray de una dimensión con los valores 100, 999, 998, 997 y 997.
import numpy as np
arr3 = np.array([100, 999, 998, 997, 997])
arr3

array([100, 999, 998, 997, 997])

In [2]:
#2. Encuentra dónde está 997.
# arr3.find(997)
# print(arr3)

In [41]:
#3. Modifica todos los valores menores de 999 a 9999.
arr4=((arr3[(arr3 < 999) & (arr3 < 9999)]) + 3)
arr4

array([ 103, 1000, 1000, 1001])

In [16]:
#4. Obtén los valores únicos del ndarray.
np.unique(arr3)

array([100, 997, 998, 999])

In [42]:
#5. Devuelve True si todos los valores son mayores que 1000.
arr4 > 1000

array([False, False, False,  True])

In [43]:
#6. Devuelve True si algún valor es mayor que 1000.
arr4 > 1000

array([False, False, False,  True])

In [45]:
#7. Ordena el array en orden ascendente.
arr3.sort()
print(arr3)

[100 997 997 998 999]
