In [1]:
#1. Define un ndarray de una dimensión con los valores 5,8 y 9.
import numpy as np
first_ndarray = np.array([5,8,9])

In [2]:
#2. Muestra su tamaño.
print(np.size(first_ndarray))

3


In [3]:
#3. Muestra el dtype.
type(first_ndarray)

numpy.ndarray

In [4]:
#4. Define un ndarray con tres dimensiones y de tipo float usando como valores 5,8 y 9.
dimensions = [5,8,9]
nd3_array = np.array(dimensions, dtype=float, ndmin=3)

print(nd3_array.ndim)
print(nd3_array.shape) #indica el tamaño de cada dimension (1 fila,1 columna, 3D )

3
(1, 1, 3)


In [9]:
#5.Define tres ndarray el primer con ceros, el segundo con unos y el último con todo vacío. Todos ellos de una dimensión con tres columnas.
arr1 = np.zeros((5,3), dtype=float)
print(arr1)
arr2 =np.ones((7,3), dtype=float)
print(arr2)
arr3 = np.empty(3)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[5. 8. 9.]
