In [7]:
#1. Define un ndarray con dos filas y dos columnas con los valores [1,2] y [3,6].
import numpy as np
arr1 = np.array([[1,2],[3,6]])
print(arr1)

[[1 2]
 [3 6]]


In [28]:
#2. Define otro ndarray con dos filas y dos columnas con los valores [6,6] y [7,7].
arr2 = np.array([[6,6],[7,7]])
print(arr2)

[[6 6]
 [7 7]]


In [29]:
#3. Multiplica el ndarray del Ejercicio 1 con el del Ejercicio 2 y almacénalo en otra variable.
multiplicacion = arr1*arr2
print(multiplicacion)

[[ 6 12]
 [21 42]]


In [30]:
#4. Suma el ndarray del Ejercicio 1 con el del Ejercicio 2.
arr1+arr2

array([[ 7,  8],
       [10, 13]])

In [6]:
#5. Suma 999 a cada elemento del ndarray del Ejercicio 1.
999+arr1

array([[1000, 1001],
       [1002, 1005]])